// =============================================================================
// connections.yaml serializer (PLE-137 visual connection editor).
// -----------------------------------------------------------------------------
// Byte-compatible with scripts/gen-yaml.ts so a file written by the editor
// produces the SAME diff a `npm run gen:yaml` run would — no spurious churn,
// clean round-trip through the PLE-136 loader. Header string + stringify opts
// are kept identical to the generator on purpose.
// =============================================================================

import { stringify } from "yaml";
import type { Edge } from "../data/types";

/** Identical to scripts/gen-yaml.ts HEADER so editor + generator output match. */
export const YAML_HEADER =
  "# GENERATED by scripts/gen-yaml.ts (PLE-136). Edit content.ts then `npm run gen:yaml`,\n" +
  "# or — once content.ts is retired — edit this file directly. Validated by src/data/schema.ts.\n";

/** lineWidth:0 disables wrapping so long labels stay on one logical scalar. */
const STRINGIFY_OPTS = { lineWidth: 0 } as const;

/** Serialise an Edge[] to the exact connections.yaml on-disk format. */
export function serializeConnections(connections: Edge[]): string {
  return YAML_HEADER + stringify({ connections }, STRINGIFY_OPTS);
}
