// =============================================================================
// YAML serializers for the visual editor (PLE-137 connections + PLE-138 nodes/
// lanes).
// -----------------------------------------------------------------------------
// Byte-compatible with scripts/gen-yaml.ts so a file written by the editor
// produces the SAME diff a `npm run gen:yaml` run would — no spurious churn,
// clean round-trip through the PLE-136 loader. Header string + stringify opts
// are kept identical to the generator on purpose.
// =============================================================================

import { stringify } from "yaml";
import type { Citation, DemandModel, Edge, IsoDate, Lane, TimelineNode } from "../data/types";

/** Identical to scripts/gen-yaml.ts HEADER so editor + generator output match. */
export const YAML_HEADER =
  "# GENERATED by scripts/gen-yaml.ts (PLE-136). Edit content.ts then `npm run gen:yaml`,\n" +
  "# or — once content.ts is retired — edit this file directly. Validated by src/data/schema.ts.\n";

/** lineWidth:0 disables wrapping so long labels/bodies stay on one logical scalar. */
const STRINGIFY_OPTS = { lineWidth: 0 } as const;

/** Serialise an Edge[] to the exact connections.yaml on-disk format. */
export function serializeConnections(connections: Edge[]): string {
  return YAML_HEADER + stringify({ connections }, STRINGIFY_OPTS);
}

/** The non-node payload of nodes.yaml the editor preserves verbatim. */
export interface NodesMeta {
  anchorDate: IsoDate;
  demandModel: DemandModel;
  citations: Citation[];
}

/**
 * Rebuild a node in the canonical types.ts field order, dropping optional fields
 * (`isAntecedent`, `keyFacts`) when unset — exactly how gen-yaml serialises the
 * content.ts literals — so editor writes diff cleanly against the generator.
 */
export function normalizeNode(n: TimelineNode): TimelineNode {
  const out: TimelineNode = {
    id: n.id,
    type: n.type,
    title: n.title,
    date: n.date,
    dateStart: n.dateStart,
    dateEnd: n.dateEnd,
    thread: n.thread,
    summary: n.summary,
    bodyMd: n.bodyMd,
    demandScore: n.demandScore,
    media: n.media,
    citationIds: n.citationIds,
    confidence: n.confidence,
  };
  if (n.isAntecedent) out.isAntecedent = true;
  if (n.keyFacts && n.keyFacts.length) out.keyFacts = n.keyFacts;
  return out;
}

/** Serialise the full nodes.yaml document (meta preserved + edited nodes). */
export function serializeNodes(meta: NodesMeta, nodes: TimelineNode[]): string {
  return (
    YAML_HEADER +
    stringify(
      {
        anchorDate: meta.anchorDate,
        demandModel: meta.demandModel,
        citations: meta.citations,
        nodes: nodes.map(normalizeNode),
      },
      STRINGIFY_OPTS,
    )
  );
}

/** Serialise the lane registry to the exact lanes.yaml on-disk format. */
export function serializeLanes(lanes: Lane[]): string {
  return YAML_HEADER + stringify({ lanes }, STRINGIFY_OPTS);
}
