// =============================================================================
// content.ts → YAML generator (PLE-136 scope 2).
// -----------------------------------------------------------------------------
// Serialises the canonical TS content (src/data/content.ts) + lane registry
// (src/data/lanes.ts) to the three runtime YAML files in public/data/. Because
// it serialises the EXACT runtime objects, the migration is lossless by
// construction; loader.test.ts proves the round-trip (YAML === content.ts).
//
//   Run:  npm run gen:yaml      (npx vite-node scripts/gen-yaml.ts)
//
// content.ts remains the authoring/test source for now; these YAML files are the
// deployed runtime source the app fetches. Keep them in lockstep via the gen
// script + round-trip test until content.ts is retired in favour of YAML-only.
// =============================================================================

import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { stringify } from "yaml";
import TIMELINE_DATA from "../src/data/content";
import { LANES } from "../src/data/lanes";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, "../public/data");
mkdirSync(outDir, { recursive: true });

// lineWidth:0 disables line-wrapping so long markdown bodies stay on one logical
// scalar (readable diffs, clean round-trip). Stable key order from the objects.
const opts = { lineWidth: 0 } as const;

const HEADER = "# GENERATED by scripts/gen-yaml.ts (PLE-136). Edit content.ts then `npm run gen:yaml`,\n# or — once content.ts is retired — edit this file directly. Validated by src/data/schema.ts.\n";

function write(name: string, doc: unknown) {
  const path = resolve(outDir, name);
  writeFileSync(path, HEADER + stringify(doc, opts), "utf8");
  // eslint-disable-next-line no-console
  console.log(`wrote ${path}`);
}

write("nodes.yaml", {
  anchorDate: TIMELINE_DATA.anchorDate,
  demandModel: TIMELINE_DATA.demandModel,
  citations: TIMELINE_DATA.citations,
  nodes: TIMELINE_DATA.nodes,
});

write("lanes.yaml", { lanes: LANES });

write("connections.yaml", { connections: TIMELINE_DATA.edges });

// eslint-disable-next-line no-console
console.log(
  `\n✓ ${TIMELINE_DATA.nodes.length} nodes, ${TIMELINE_DATA.edges.length} connections, ` +
    `${LANES.length} lanes, ${TIMELINE_DATA.citations.length} citations`,
);
